### ISSUE TITLE
Crash in MetalVideoMixerImpl.swift line 406

### ISSUE THREAD

**Issue by tuanback** [cats-oss/VideoCast-Swift#39]
Thank you for your effort and hard word to make this library.

It works well but unfortunately, I am facing a Crashing bug sometimes.

![Screen Shot 2019-10-07 at 1 52 05 PM](https://user-images.githubusercontent.com/13817148/66285953-1c954480-e90a-11e9-9a29-4c1e7af64260.png)

Device: iPhone 6s
OS version: 12.3.1

Do you have any ideas about how to fix this bug?

Thanks in advance

**Comment by thmatuza** [comment]
Thank you for reporting it.
Fixed it.
https://github.com/cats-oss/VideoCast-Swift/pull/40
